using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
namespace Qingling {
public static class ComfortTests {
 static readonly List<string> passed=new List<string>();
 static void Check(bool ok,string label){if(!ok)throw new Exception(label);passed.Add(label);}
 public static void Run(){
  Check(AnimationEngine.Timing(16).Sum()==2600&&AnimationEngine.FrameCount(16)==32,"Sitting uses a smooth relaxed 2.6 second cycle");var sitSlow=new AnimationEngine{DockRow=16};var sitFast=new AnimationEngine{DockRow=16};bool calm=true;for(int i=0;i<100;i++)calm&=sitSlow.Frame(i*.05,1)==sitFast.Frame(i*.05,3);Check(calm,"Global fast action speed does not accelerate seated swaying");
  Check(AnimationEngine.Timing(17).Sum()==3600&&AnimationEngine.FrameCount(17)==24,"Sleeping uses a slow 3.6 second breathing loop");var sleepSlow=new AnimationEngine{PreviewRow=17};var sleepFast=new AnimationEngine{PreviewRow=17};bool peaceful=true;for(int i=0;i<100;i++)peaceful&=sleepSlow.Frame(i*.05,1)==sleepFast.Frame(i*.05,3);Check(peaceful,"Global fast action speed does not accelerate sleeping");
  var rightDrag=new AnimationEngine{DragRow=1};int run=rightDrag.Frame(0,1);Check(run>=8&&run<16,"Every rightward drag uses the original large-stride run");var leftDrag=new AnimationEngine{DragRow=2};run=leftDrag.Frame(0,1);Check(run>=16&&run<24,"Every leftward drag uses the original large-stride run");var mappedStart=new AnimationEngine{DragRow=1,ChooseStart=(row,previous)=>23};run=mappedStart.Frame(0,1);Check(run>=8&&run<16,"Large-stride entry maps 24-frame pose selection into eight source frames");rightDrag.DragRow=11;Check(rightDrag.Frame(.1,1)>=MotionData.Index(11,0),"Vertical drag never enters the large-stride run");
  var walking=new AnimationEngine{DragRow=1};walking.Frame(0,1);int before=walking.Frame(.35,1);walking.DragRow=2;int after=walking.Frame(.35,1);Check(before-8==after-16,"Direction reversal preserves large-stride phase");walking.DragRow=1;Check(walking.Frame(.35,1)==before,"Repeated left-right reversal does not restart feet");
  var c=new ReadingClock();c.Arm(0,20);Check(!c.Tick(19,false),"Reply remains for reading duration");Check(!c.Tick(100,true),"Hover pauses remaining time");Check(c.Tick(102,false)&&!c.Tick(103,false),"Timeout fires once after hover ends");c.Arm(200,20);c.Stop();Check(!c.Tick(1000,false),"Streaming disarms reading timeout");
  foreach(var target in new[]{new Point(-100,100),new Point(500,100),new Point(150,-100),new Point(150,400)}){var p=BubbleArrow.Points(new Size(330,208),target);Point basePoint=new Point((p[0].X+p[2].X)/2,(p[0].Y+p[2].Y)/2);Check(Vector.Multiply(p[1]-basePoint,target-basePoint)>0,"Tail points toward target "+target);}
  var b1=new BlinkClock();var b2=new BlinkClock();var slow=new AnimationEngine();var fast=new AnimationEngine();int episodes=0,last=-1;
  bool same=true;for(int i=0;i<6000;i++){double t=i*.01;slow.Frame(t,.25);fast.Frame(t,3);int a=b1.Frame(t,5,true),b=b2.Frame(t,5,true);same&=a==b;if(a>=0&&last<0)episodes++;last=a;}Check(same,"Blink independent of animation speed");Check(episodes>=9&&episodes<=14,"Comfortable 4–6 second blink interval over one minute");
  var config=Json.Read<Settings>("{\"Model\":\"old-profile\"}");Check(config.BubbleSeconds==20&&config.BlinkSeconds==5&&!config.InputHidden,"Old settings receive compatible defaults");
  foreach(int row in new[]{0,1,2,3,4,5,6,7,8,11,12,13,14,15,16,17}){var engine=new AnimationEngine{PreviewRow=row};var ids=new HashSet<int>();for(int n=0;n<500;n++)ids.Add(engine.Frame(n*.01,1));Check(ids.Count==MotionData.Counts[row]&&ids.Count>8,"Every animation uses all expanded frames "+row);}
 }
 static void Capture(Window w,string path){w.UpdateLayout();var b=new RenderTargetBitmap((int)w.Width,(int)w.Height,96,96,PixelFormats.Pbgra32);b.Render(w.Content as System.Windows.Media.Visual);var e=new PngBitmapEncoder();e.Frames.Add(BitmapFrame.Create(b));using(var f=File.Create(path))e.Save(f);}
 public static void Ui(DesktopApp app,string path){Directory.CreateDirectory(path);var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(400)};int step=0;Window blocker=null;
  timer.Tick+=(s,e)=>{try{
   if(step==0){Run();app.Bubbles.Draft="隐藏也保留这段草稿";app.Bubbles.HideInput();app.Bubbles.Follow();Check(!app.Bubbles.Input.IsVisible&&app.Config.InputHidden,"Input completely hidden and stays hidden during follow");app.Bubbles.Greet("测试问候");Check(!app.Bubbles.Input.IsVisible,"Greeting does not restore hidden input");app.Bubbles.Show(false);Check(!app.Bubbles.Input.IsVisible,"Settings/startup preserve hidden input");app.Bubbles.ShowInput();Check(app.Bubbles.Input.IsVisible&&app.Bubbles.Draft.Contains("草稿"),"Menu restores hidden input and draft");app.Bubbles.End("已完成");app.Bubbles.AdvanceReading(double.MaxValue,false);Check(!app.Bubbles.Reply.IsVisible,"Real reply window hides after timeout");app.Bubbles.Begin();app.Bubbles.AdvanceReading(double.MaxValue,false);Check(app.Bubbles.Reply.IsVisible,"Real streaming reply never times out");app.Bubbles.End("测试");app.Bubbles.Greet("霖铃在这里。气泡会定时消失，箭头也会跟着我转向。");app.Pet.Dock(15,false);app.Bubbles.Follow();step++;}
   else if(step==1){Capture(app.Bubbles.Reply,Path.Combine(path,"top-bubble.png"));Capture(app.Bubbles.Input,Path.Combine(path,"input-hide-control.png"));app.Pet.Dock(16,false);blocker=new Window{Width=400,Height=40,Left=app.Pet.Left-80,Top=app.Pet.Top+app.Pet.Height-40,Topmost=true,ShowActivated=false,ShowInTaskbar=false,WindowStyle=WindowStyle.None,Background=Brushes.Gray};blocker.Show();IntPtr foreground=PetZOrder.GetForegroundWindow();var bounds=new Rect(app.Pet.Left,app.Pet.Top,app.Pet.Width,app.Pet.Height);Check(PetZOrder.Raise(app.Pet),"Native raise above another topmost window succeeds");Check(PetZOrder.GetForegroundWindow()==foreground,"Topmost repair does not steal focus");Check(bounds==new Rect(app.Pet.Left,app.Pet.Top,app.Pet.Width,app.Pet.Height),"Topmost repair preserves position and size");IntPtr h=new WindowInteropHelper(app.Pet).Handle,bh=new WindowInteropHelper(blocker).Handle;bool above=false;for(IntPtr p=PetZOrder.GetWindow(bh,3);p!=IntPtr.Zero;p=PetZOrder.GetWindow(p,3))if(p==h){above=true;break;}Check(above,"Pet is above simulated raised taskbar in native Z order");blocker.Close();blocker=null;Capture(app.Pet,Path.Combine(path,"sitting.png"));step++;}
   else{Capture(app.Pet,Path.Combine(path,"sitting.png"));File.WriteAllText(Path.Combine(path,"comfort-tests.json"),Json.Write(new{ok=true,checks=passed.Count,tests=passed.Distinct().ToArray()}),Encoding.UTF8);timer.Stop();app.Quit();}
  }catch(Exception ex){if(blocker!=null)blocker.Close();File.WriteAllText(Path.Combine(path,"comfort-tests.json"),Json.Write(new{ok=false,error=ex.ToString(),tests=passed.Distinct().ToArray()}),Encoding.UTF8);timer.Stop();app.Quit();}};timer.Start();
 }
 public static void Performance(DesktopApp app,string path){Directory.CreateDirectory(path);var watch=System.Diagnostics.Stopwatch.StartNew();var process=System.Diagnostics.Process.GetCurrentProcess();var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(500)};double cpu=0,start=0;long peak=0;int step=0;int[] rows={0,1,2,3,4,5,6,7,8,11,12,13,14,15,16,17};app.Config.FollowMouse=false;app.Config.RandomActions=false;app.Bubbles.Hide();
  timer.Tick+=(s,e)=>{process.Refresh();peak=Math.Max(peak,process.WorkingSet64);if(step==4){cpu=process.TotalProcessorTime.TotalSeconds;start=watch.Elapsed.TotalSeconds;}if(step>=4)app.Pet.Preview(rows[(step-4)%rows.Length]);if(step++<28)return;double seconds=watch.Elapsed.TotalSeconds-start,used=process.TotalProcessorTime.TotalSeconds-cpu;File.WriteAllText(Path.Combine(path,"performance.json"),Json.Write(new{ok=true,seconds=seconds,cpuSeconds=used,oneCorePercent=used/seconds*100,machinePercent=used/seconds/Environment.ProcessorCount*100,logicalProcessors=Environment.ProcessorCount,workingSetMB=process.WorkingSet64/1048576.0,peakSampledWorkingSetMB=peak/1048576.0,description="All 16 animations cycled at default size; no live API request; local machine sample, not a universal performance guarantee."}),Encoding.UTF8);timer.Stop();app.Quit();};timer.Start();
 }
}
}
